# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190418_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, max_length=2, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_years',
            field=models.IntegerField(default=0, max_length=2, verbose_name='工作年限'),
        ),
    ]
