# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190418_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('jsj', '计算机'), ('jjx', '经济学'), ('gl', '管理'), ('ky', '考研'), ('lgbx', '理工补习'), ('slj', '四六级'), ('xlx', '心理学'), ('wy', '外语'), ('wxwh', '文学文化'), ('yssj', '艺术设计'), ('ls', '历史'), ('zx', '哲学'), ('fx', '法学'), ('gx', '工学'), ('lx', '理学'), ('yyws', '医药卫生'), ('nlyy', '农林园艺')], default='计算机', max_length=20, verbose_name='课程类别'),
        ),
    ]
