# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190507_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
